export const QUERY_KEYS = {
  LOG_IN: "logIn",
  PERMISSIONS: "permissions",
  ROLES: "roles",
  ROLE_DETAILS: "roleDetails",
  ROLE_PERMISSIONS: "rolePermissions",
  USERS: "users",
  CATEGORIES: "categories",
  CATEGORIES_TYPES: "categoriesTypes",
  PRODUCTS: "products",
  PRODUCT_DETAILS: "productDetails",
  ORDERS: "orders",
  ORDER_DETAILS: "orderDetails",
  DASHBOARD_OVERVIEW: "dashboardOverview",
  ANALYTICS_PRODUCTS: "analyticsProducts",
};
