export const permissionsData = {
  columns: [
    { Header: "اسم الصلاحية", accessor: "name", width: "22%" },
    { Header: "الكود", accessor: "key", width: "16%" },
    { Header: "الموديول", accessor: "module", width: "14%" },
    { Header: "الأوامر", accessor: "actions", width: "18%" },
    { Header: "آخر تحديث", accessor: "updatedAt", width: "10%" },
    { Header: "إجراءات", accessor: "actionsMenu", width: "8%" },
  ],
  rows: [
    {
      name: "إدارة المنتجات",
      key: "products_manage",
      module: "المنتجات",
      actions: ["view", "create", "update", "delete"].join(" · "),
      status: "مفعّل",
      rolesCount: 3,
      updatedAt: "2025-08-10 14:21",
    },
    {
      name: "عرض المنتجات",
      key: "products_view",
      module: "المنتجات",
      actions: ["view"].join(" · "),
      status: "مفعّل",
      rolesCount: 5,
      updatedAt: "2025-08-08 10:03",
    },
    {
      name: "إنشاء منتج",
      key: "products_create",
      module: "المنتجات",
      actions: ["create"].join(" · "),
      status: "موقّف",
      rolesCount: 1,
      updatedAt: "2025-08-01 09:40",
    },
    {
      name: "إدارة الطلبات",
      key: "orders_manage",
      module: "الطلبات",
      actions: ["view", "update", "refund"],
      status: "مفعّل",
      rolesCount: 2,
      updatedAt: "2025-08-11 18:05",
    },
    {
      name: "إدارة المستخدمين",
      key: "users.manage",
      module: "المستخدمون",
      actions: ["view", "create", "update", "delete", "resetPassword"],
      status: "مفعّل",
      rolesCount: 2,
      updatedAt: "2025-08-09 12:11",
    },
    {
      name: "عرض التقارير",
      key: "reports.view",
      module: "التقارير",
      actions: ["view", "export"],
      status: "مفعّل",
      rolesCount: 4,
      updatedAt: "2025-08-07 16:33",
    },
    {
      name: "إدارة الإعدادات",
      key: "settings.manage",
      module: "الإعدادات",
      actions: ["update"],
      status: "موقّف",
      rolesCount: 1,
      updatedAt: "2025-08-03 08:20",
    },
  ],
};

export default permissionsData;
